name: Docker Compose Test

on:
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: docker/setup-buildx-action@v1
      with:
        docker-version: '20.10.9'

    - name: Set up Docker Compose
      uses: docker/compose@v2.2.3
      with:
        compose-version: '2.0.0'

    - name: Construye y ejecuta contenedores
      run: |
        docker-compose build
        docker-compose up -d

    - name: Baja contenedores
      run: docker-compose down
