name: Docker Compose Test

on:
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Construye y ejecuta contenedores
      run: |
        docker-compose up -d

    - name: Baja contenedores
      run: docker-compose down
